# Site settings
title: Xander
email: tod.xander@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://todd-xander.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: Todd Xander's Blog

# Social icons
google: "107899685947493255112"
linkedin: todd-xander-40267154
github: todd-xander
email: tod.xander@gmail.com

footer: © Taken theme

# Build settings
markdown: kramdown
highlighter: rouge


safe: false
plugin: ./_plugins
gems: [jekyll-paginate]
paginate: 4
paginate_path: /page:num
